<a href="https://colab.research.google.com/github/linoyElimeleh/practical-neural-networks-with-keras-heb/blob/main/Lesson2_backpropegation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preproccessing

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import keras.datasets.mnist as mnist

In [3]:
#Load data
((trainData,trainLabels),(testData,testLabels))= mnist.load_data();

print("trainData.shape: ",trainData.shape)
print("tranLables.shape",trainLabels.shape)

trainData.shape:  (60000, 28, 28)
tranLables.shape (60000,)


In [4]:
print("testData.shape",testData.shape)

testData.shape (10000, 28, 28)


In [5]:
print("testLabels.shape",testLabels.shape)

testLabels.shape (10000,)


In [7]:
print(trainData[0])
print()

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18

In [9]:
#prepare data to 0,1
firstDigit = np.where(trainData[0]>0, 1, 0)
print(firstDigit)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 

In [11]:
print(trainLabels[0])

5


In [12]:
# To all the data
trainData=np.where(trainData>0, 1, 0)
testData=np.where(testData>0, 1, 0)

In [14]:
# change the scales to 1 dimend
trainData=trainData.reshape(trainData.shape[0],-1)
print("trainData.shape after reshape: ",trainData.shape)


trainData.shape after reshape:  (60000, 784)


In [15]:
# change the scales to 1 dimend
testData=testData.reshape(testData.shape[0],-1)
print("testData.shape after reshape: ",testData.shape)


testData.shape after reshape:  (10000, 784)


In [17]:
def ToOneHot(n):
    return [ (int)(i==n) for i in range(10)]


oneHotTrainLebels=np.ndarray((trainLabels.shape[0],10))
for i in range(len(trainLabels)):
    oneHotTrainLebels[i]=ToOneHot(trainLabels[i])

print("oneHotTrainLebels.shape: ",oneHotTrainLebels.shape)

oneHotTrainLebels.shape:  (60000, 10)


In [18]:
oneHotTestLebels=np.ndarray((testLabels.shape[0],10))
for i in range(len(testLabels)):
    oneHotTestLebels[i]=ToOneHot(testLabels[i])

print("oneHotTestLebels.shape: ",oneHotTestLebels.shape)

oneHotTestLebels.shape:  (10000, 10)


In [19]:
trainDataTuples=[]
for i in range(len(trainData)):
    trainDataTuples.append((trainData[i],oneHotTrainLebels[i]))

print("trainDataTuples[0]: ",type(trainDataTuples[0]))
print("trainDataTuples[0].shape: (",trainDataTuples[0][0].shape,",",trainDataTuples[0][1].shape,")")


trainDataTuples[0]:  <class 'tuple'>
trainDataTuples[0].shape: ( (784,) , (10,) )


In [20]:
testDataTuples=[]
for i in range(len(testData)):
    testDataTuples.append((testData[i],oneHotTestLebels[i]))


#Implement Network

In [21]:
#Create network
#create metrics in 50*784 dim with 0-1 values randomly
w1=np.random.randn(50,784)
w2=np.random.randn(10,50)
print("w1.shape: ",w1.shape)
print("w2.shape:", w2.shape )

w1.shape:  (50, 784)
w2.shape: (10, 50)


In [22]:
b1=np.random.randn(50,1)
b2=np.random.randn(10,1)
print("b1.shape: ",b1.shape)
print("b2.shape:", b2.shape )


b1.shape:  (50, 1)
b2.shape: (10, 1)


In [26]:
def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))

def LosFunctionGradiant(a,y):
    return a-y

def sigmoidDerivative(x):
    return sigmoid(x)*(1-sigmoid(x))

def CalcError(y,a):
    e=pow(y-a,2)
    res=(1/2)* e
    s=np.sum(res,0)
    return s

In [27]:
#feed foreword digit 0

x=trainData[0].reshape(trainData[0].shape[0],1)
print("Transpose first digit")
print(x.shape)
u1=np.dot(w1,x)
print(u1.shape)
z1=u1+b1
f1=sigmoid(z1)
u2=np.dot(w2,f1)
z2=u2+b2
f2=sigmoid(z2)
print("f1")
print(f1)
print()
print("f2")
print(f2)

Transpose first digit
(784, 1)
(50, 1)
f1
[[9.99657700e-01]
 [2.00358070e-10]
 [9.96227546e-01]
 [6.07938753e-01]
 [2.26722747e-03]
 [1.14919895e-07]
 [9.96717322e-01]
 [4.29246062e-01]
 [7.92682699e-01]
 [9.95475467e-01]
 [1.57592205e-04]
 [4.89229602e-05]
 [9.99949300e-01]
 [9.99998746e-01]
 [2.01367491e-06]
 [4.87505626e-05]
 [1.41084936e-01]
 [2.24060718e-01]
 [9.98045923e-01]
 [6.52976650e-01]
 [9.90792269e-01]
 [7.96352342e-04]
 [5.57469603e-01]
 [9.85474522e-03]
 [9.99997841e-01]
 [1.44541781e-04]
 [5.11286993e-03]
 [4.69569493e-04]
 [9.95527346e-01]
 [8.57500002e-03]
 [9.87788245e-08]
 [9.99651702e-01]
 [3.58665511e-02]
 [9.99541362e-01]
 [4.51932322e-05]
 [9.98742159e-01]
 [9.99989771e-01]
 [9.93114811e-01]
 [9.99999995e-01]
 [9.99997583e-01]
 [2.83557798e-04]
 [8.49869837e-05]
 [9.99118348e-01]
 [9.99948376e-01]
 [2.09476522e-06]
 [1.00000000e+00]
 [9.73832208e-01]
 [5.33543871e-05]
 [9.99979962e-01]
 [9.36966018e-01]]

f2
[[6.97715786e-05]
 [1.57800280e-01]
 [5.98538413e-02]

# Training

In [28]:
epochs=50
minibatchSize=10
eta=3


for i in range(epochs):
     numOfTrue=0
     numOfFalse=0
     print("epoch "+str(i))
     globalError=0
     np.random.shuffle(trainDataTuples)
     numOfMinibatchs=(int)(len(trainDataTuples)/minibatchSize)
     minibatchPos=0

     for j in range(numOfMinibatchs):
         minibatchPos=j*minibatchSize
         minibatchData=trainDataTuples[minibatchPos:minibatchPos+minibatchSize]
         w2GradientErr=np.zeros(w2.shape)
         w1GradientErr=np.zeros(w1.shape)
         b1GradientErr=np.zeros(b1.shape)
         b2GradientErr=np.zeros(b2.shape)
         eMiniBatch=0
         for i in range(minibatchSize):
            miniTuple=minibatchData[i]
            x=miniTuple[0].reshape(miniTuple[0].shape[0],1)
            y=miniTuple[1].reshape(miniTuple[1].shape[0],1)


            #feedforword
            a0=x
            z1=np.dot(w1,x)+b1
            a1=sigmoid(z1)
            z2=np.dot(w2,a1)+b2
            a2=sigmoid(z2)

            c=np.argmax(a2)
            l=np.argmax(y)
            if (c==l):
                numOfTrue+=1
            else:
                numOfFalse+=1

            #errL  calculate last level error
            errL=LosFunctionGradiant(a2,y)*sigmoidDerivative(z2)
            v2=np.dot(errL,a1.T)
            w2GradientErr+=v2
            b2GradientErr+=errL


            #calculate last-1 level error
            errF=np.dot((w2.T),errL)*sigmoidDerivative(z1)
            v1=np.dot(errF,a0.T)
            w1GradientErr+=v1
            b1GradientErr+=errF
            e=CalcError(y,a2)
            eMiniBatch+=e
         #Update w and b
         w1=w1-(eta/minibatchSize)*w1GradientErr
         w2=w2-(eta/minibatchSize)*w2GradientErr
         b1=b1-(eta/minibatchSize)*b1GradientErr
         b2=b2-(eta/minibatchSize)*b2GradientErr

         globalError+=eMiniBatch/minibatchSize
     globalError/=numOfMinibatchs
     print("globalError")
     print(globalError)
     print("NumOfTrue")
     print(numOfTrue)
     print("numOfFalse")
     print(numOfFalse)
     print(str(numOfTrue/600)+"%")
     #evaluation
     evalTrue=0
     evalFalse=0
     for testData in testDataTuples:
        x=testData[0].reshape(testData[0].shape[0],1)
        y=testData[1].reshape(testData[1].shape[0],1)
        z1=np.dot(w1,x)+b1
        a1=sigmoid(z1)
        z2=np.dot(w2,a1)+b2
        a2=sigmoid(z2)

        c=np.argmax(a2)
        l=np.argmax(y)
        if (c==l):
            evalTrue+=1
        else:
            evalFalse+=1
     print("evalTrue")
     print(evalTrue)
     print("evalFalse")
     print(evalFalse)
     print(str(evalTrue/100)+"%")

epoch 0
globalError
[0.19698224]
NumOfTrue
42111
numOfFalse
17889
70.185%
evalTrue
8243
evalFalse
1757
82.43%
epoch 1
globalError
[0.11396398]
NumOfTrue
49988
numOfFalse
10012
83.31333333333333%
evalTrue
8375
evalFalse
1625
83.75%
epoch 2
globalError
[0.10351509]
NumOfTrue
50681
numOfFalse
9319
84.46833333333333%
evalTrue
8460
evalFalse
1540
84.6%
epoch 3
globalError
[0.09698415]
NumOfTrue
51111
numOfFalse
8889
85.185%
evalTrue
8508
evalFalse
1492
85.08%
epoch 4
globalError
[0.07818201]
NumOfTrue
53512
numOfFalse
6488
89.18666666666667%
evalTrue
9361
evalFalse
639
93.61%
epoch 5
globalError
[0.05053058]
NumOfTrue
56525
numOfFalse
3475
94.20833333333333%
evalTrue
9392
evalFalse
608
93.92%
epoch 6
globalError
[0.04652926]
NumOfTrue
56801
numOfFalse
3199
94.66833333333334%
evalTrue
9396
evalFalse
604
93.96%
epoch 7
globalError
[0.04406092]
NumOfTrue
56932
numOfFalse
3068
94.88666666666667%
evalTrue
9440
evalFalse
560
94.4%
epoch 8
globalError
[0.04156153]
NumOfTrue
57115
numOfFalse
2885
9