<a href="https://colab.research.google.com/github/linoyElimeleh/practical-neural-networks-with-keras-heb/blob/main/Lesson1_Numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

כפל מטריצות

In [ ]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
b= np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
c= a.dot(b)
print(c)

[[22 28]
 [49 64]]


In [ ]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print(a)
b= np.array([[1,2],[3,4],[5,6]])
print(b)
c= a.dot(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


חיבור מטריצות

In [ ]:
a= np.array([[1,2],[3,4],[5,6]])
print(a)
b= np.array([[11,12],[13,14],[15,16]])
print(b)

c=a+b
print(c)

[[1 2]
 [3 4]
 [5 6]]
[[11 12]
 [13 14]
 [15 16]]
[[12 14]
 [16 18]
 [20 22]]


טרנספוז

In [ ]:
a= np.array([[1,2,3],[4,5,6]])
print(a)
b=a.T
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


feed forward

In [ ]:
import numpy as np
x=np.array([[10],[7],[3]])
print(x)

[[10]
 [ 7]
 [ 3]]


In [ ]:
w1=np.zeros((2,3))
w1[0]=[-7,4,14]
w1[1]=[4,-6,3]
print(w1)

[[-7.  4. 14.]
 [ 4. -6.  3.]]


In [ ]:
# ouput vector
u=w1.dot(x)
print(u)

[[0.]
 [7.]]


In [ ]:
# bias
b=np.array([-0.6,-0.3])
print(b)

[-0.6 -0.3]


In [ ]:
# reshape to a metrics
b=np.reshape(b,(1,2))
print(b)

[[-0.6 -0.3]]


In [ ]:
# transpose to ouput
b=b.T
print(b)

[[-0.6]
 [-0.3]]


In [ ]:
# adding the sum to the bias
z1=u+b
print(z1)

[[-0.6]
 [ 6.7]]


In [ ]:
# sigmoid
def sigmoid(x):
    return 1.0/(1.0+np.exp(-x))

a1=sigmoid(z1)
print(a1)

[[0.35434369]
 [0.9987706 ]]


In [ ]:
w2=np.array([[4,5]])
print(w2)

[[4 5]]


In [ ]:
u2=w2.dot(a1)
print(u2)

[[6.41122778]]


In [ ]:
b2=np.array([[-6]])
print(b2)

[[-6]]


In [ ]:
z2=u2+b2
print(z2)

[[0.41122778]]


In [ ]:
a2=sigmoid(z2)
print(a2)

[[0.60138224]]
